define(["app"], function(app){
	return app.run(['$rootScope','$state','$stateParams',function ($rootScope,$state,$stateParams) {
	}]).config(function($stateProvider,$urlRouterProvider,$uiViewScrollProvider){
		$uiViewScrollProvider.useAnchorScroll();
		$urlRouterProvider.otherwise('/index');
		$stateProvider.state('index',{
			url:"/index",
			views:{
				'content':{
					templateUrl:"/views/systemView.html"
				},'panelPage@index':{
					templateUrl:"/views/roleView.html",
					controller:''
				}
			}
		}).state('controllerPanel',{
			url:'/controllerPanel',
			views:{
				'content':{
					templateUrl:"/views/systemView.html"
				},'panelPage@controllerPanel':{
					templateUrl:"/views/roleView.html",
					controller:'accountList'
				}
			}
		}).state('controllerPanel.roleManage',{
			url:'/roleManage',
			views:{
				'panelPage':{
					templateUrl:"/views/roleView.html",
					controller:'accountList'
				}
			}
		}).state('controllerPanel.urlManage',{
			url:'/urlManage',
			views:{
				'panelPage':{
					templateUrl:"/views/urlView.html",
					controller:'urlController'
				}
			}
		}).state('controllerPanel.nodeMange',{
			url:'/nodeMange',
			views:{
				'panelPage':{
					templateUrl:"/views/nodeView.html"
				}
			}
		}).state('controllerPanel.productManage',{
			url:'/productManage',
			views:{
				'panelPage':{
					templateUrl:"/views/product.html",
					controller:'product'
				}
			}
		}).state('controllerPanel.checkRole',{
			url:'/checkRole',
			views:{
				'panelPage':{
					templateUrl:"/views/checkRole.html",
					controller:'checkRole'
				}
			}
		}).state('userList',{
			url:'/userList',
			views:{
				'content':{
					templateUrl:"/views/userListView.html"
				}
			}
		});
	});
});